parser: '@typescript-eslint/parser'

plugins:
    - '@typescript-eslint'

extends:
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/recommended-require-type-checking

rules:
    import/no-unresolved: off
    react/prop-types: off
    react/jsx-pascal-case: off
    import/order: off
    babel/camelcase: off
    jsx-a11y/label-has-for: off
    max-lines-per-function: off
    babel/quotes: off
    consistent-return: off
    no-console: 1
