root: true
env:
    browser: true

parser: '@typescript-eslint/parser'
parserOptions:
    project: './tsconfig.json'

plugins:
    - '@typescript-eslint'

extends:
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'
    _ 'prettier'
    _ 'prettier/react'
    _ 'prettier/@typescript-eslint'

rules:
    import/no-unresolved: off
    no-unused-vars:
        - error
        - 
            vars: 'all'
            args: 'after-used'
            ignoreRestSiblings: 'false'
    react/prop-types: off
    react/jsx-pascal-case: off
    import/order: off
    babel/camelcase: off
    jsx-a11y/label-has-for: off
    max-lines-per-function: off
    babel/quotes: off
    consistent-return: off
    no-console: 1
    space-in-brackets:
        - 'always'

overrides:
    - files:
          - 'src/**/*.ts'
          - 'src/**/*.tsx'
