[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
  
[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
  package = "netlify-plugin-minify-html"
  
[plugins.inputs.minifierOptions]
  minifyCSS = true